//! Dependency unification — no code, on purpose.
//!
//! This crate exists so every third-party dependency is compiled once, with
//! the one feature set the workspace uses, whichever crate Cargo starts from:
//! its `Cargo.toml` names each of them with that set, and every member
//! depends on it. The table is generated by cargo-hakari (`just hakari`);
//! see `docs/architecture/crates/deps.md`.
