//! pi and Oh My Pi → session events, through an extension of ours.
//!
//! Neither runs shell hooks; both load a TypeScript extension for one launch
//! with `-e <file>`. The extension below subscribes to the lifecycle events a
//! row reads and shells out to the reporter with one compact JSON line per
//! event. Its source is generated here so the reporter argv is baked in, and
//! the file lives under the session's run directory, never in a project.

use super::{args_summary, first_str};
use bisa_core::ToolTier;
use bisa_harness::{
    InputRequest, LaunchFile, LifecycleEvent, ProgressEvent, ReportingContext, ReportingPlan,
    SessionEvent,
};
use serde_json::Value;

/// The extension: one `pi.on` per event, one `pi.exec` per report.
fn extension_source(reporter: &[String]) -> String {
    let argv = serde_json::to_string(reporter).unwrap_or_else(|_| "[]".into());
    format!(
        r#"// Generated by Bisa for one interactive session: reports what this
// harness is doing to the workspace it was opened from. Never edited by hand.
const REPORTER = {argv};
const EVENTS = [
  "session_start", "agent_start", "agent_end",
  "tool_execution_start", "tool_execution_end",
  "tool_approval_requested", "tool_approval_resolved",
  "ui_prompt_start", "ui_prompt_end",
];
function compact(event) {{
  const out = {{}};
  if (!event || typeof event !== "object") return out;
  for (const key of ["toolName", "tool", "name", "id", "toolCallId", "callId", "message", "text", "prompt", "title", "model"]) {{
    const v = event[key];
    if (typeof v === "string") out[key] = v.slice(0, 200);
  }}
  const args = event.input !== undefined ? event.input : event.args;
  if (args !== undefined) {{
    try {{ out.input = JSON.stringify(args).slice(0, 200); }} catch {{}}
  }}
  if (typeof event.isError === "boolean") out.isError = event.isError;
  if (typeof event.isTerminal === "boolean") out.isTerminal = event.isTerminal;
  return out;
}}
export default function (pi) {{
  for (const name of EVENTS) {{
    pi.on(name, async (event) => {{
      const payload = JSON.stringify({{ event: name, ...compact(event) }});
      try {{ await pi.exec(REPORTER[0], [...REPORTER.slice(1), payload]); }} catch {{}}
    }});
  }}
}}
"#
    )
}

pub fn reporting(ctx: &ReportingContext) -> ReportingPlan {
    let file = LaunchFile {
        name: "bisa-reporter.ts".into(),
        contents: extension_source(&ctx.reporter),
    };
    let path = ctx.files_dir.join(&file.name).display().to_string();
    ReportingPlan {
        files: vec![file],
        args: vec!["-e".into(), path],
        intercept_approval_notifications: false,
        pull: None,
    }
}

fn tool(payload: &Value) -> String {
    first_str(payload, &["toolName", "tool", "name"])
        .unwrap_or("tool")
        .to_string()
}

fn request_id(payload: &Value) -> String {
    first_str(payload, &["id", "toolCallId", "callId"])
        .map(str::to_string)
        .unwrap_or_else(|| tool(payload))
}

/// A tool call's own id (`toolCallId`), when the event carries one.
fn call_id(payload: &Value) -> Option<String> {
    first_str(payload, &["toolCallId", "callId"])
        .filter(|id| !id.is_empty())
        .map(str::to_string)
}

/// One extension report → what it means.
pub fn translate(payload: &Value) -> Vec<SessionEvent> {
    let Some(event) = payload.get("event").and_then(|e| e.as_str()) else {
        return Vec::new();
    };
    let input = payload.get("input").cloned().unwrap_or(Value::Null);
    match event {
        "session_start" => vec![SessionEvent::Lifecycle(LifecycleEvent::Started)],
        // A turn starts — on the model the extension names, when it does.
        "agent_start" => {
            let mut events = vec![SessionEvent::Progress(ProgressEvent::TurnStarted)];
            let model = first_str(payload, &["model"]).or_else(|| first_str(&input, &["model"]));
            if let Some(model) = model.filter(|m| !m.is_empty()) {
                events.push(SessionEvent::Progress(ProgressEvent::ModelChanged {
                    model: model.to_string(),
                }));
            }
            events
        }
        // OMP says `agent_end` for every retry of a turn, `isTerminal`
        // telling the last from the rest: only the last is the turn's end.
        "agent_end" => match payload.get("isTerminal").and_then(|t| t.as_bool()) {
            Some(false) => Vec::new(),
            _ => vec![SessionEvent::Progress(ProgressEvent::TurnEnded)],
        },
        "tool_execution_start" => {
            let name = tool(payload);
            vec![SessionEvent::Progress(ProgressEvent::ToolStarted {
                tier: ToolTier::classify(&name.to_ascii_lowercase()),
                args_summary: args_summary(&input),
                name,
                id: call_id(payload),
            })]
        }
        // `tool_execution_end` carries `isError`: the tool's own verdict.
        "tool_execution_end" => vec![SessionEvent::Progress(ProgressEvent::ToolEnded {
            name: tool(payload),
            ok: payload.get("isError").and_then(|e| e.as_bool()) != Some(true),
            id: call_id(payload),
        })],
        "tool_approval_requested" => {
            let name = tool(payload);
            vec![SessionEvent::Lifecycle(LifecycleEvent::InputRequested {
                request: InputRequest::permission(
                    request_id(payload),
                    name.clone(),
                    ToolTier::classify(&name.to_ascii_lowercase()),
                    args_summary(&input),
                    input.clone(),
                ),
            })]
        }
        "ui_prompt_start" => vec![SessionEvent::Lifecycle(LifecycleEvent::InputRequested {
            request: InputRequest::question(
                request_id(payload),
                first_str(payload, &["message", "text", "prompt", "title"])
                    .unwrap_or("The agent has a question")
                    .to_string(),
                Vec::new(),
            ),
        })],
        "tool_approval_resolved" | "ui_prompt_end" => {
            vec![SessionEvent::Lifecycle(LifecycleEvent::InputResolved {
                id: request_id(payload),
            })]
        }
        _ => Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn the_extension_bakes_the_reporter_in_and_is_passed_for_one_launch() {
        let ctx = ReportingContext {
            session: "01S".into(),
            reporter: vec![
                "/bin/bisa".into(),
                "session".into(),
                "report".into(),
                "--harness".into(),
                "omp".into(),
            ],
            files_dir: "/ws/run/interactive/01S".into(),
            port: None,
            guard: None,
            guard_timeout_secs: 0,
        };
        let plan = reporting(&ctx);
        assert_eq!(
            plan.args,
            ["-e", "/ws/run/interactive/01S/bisa-reporter.ts"]
        );
        let src = &plan.files[0].contents;
        assert!(
            src.contains(r#"const REPORTER = ["/bin/bisa","session","report","--harness","omp"];"#)
        );
        assert!(src.contains("tool_approval_requested"));
        assert!(
            src.contains("isError"),
            "the extension forwards the tool's verdict"
        );
        assert!(
            src.contains("isTerminal") && src.contains(r#""model""#) && src.contains("event.args"),
            "the extension forwards the turn's last word, the model and the tool's arguments"
        );
        // OMP says `agent_end` for every retry of a turn; only the last ends it.
        assert!(translate(&json!({"event": "agent_end", "isTerminal": false})).is_empty());
        assert!(matches!(
            translate(&json!({"event": "agent_end", "isTerminal": true}))[0],
            SessionEvent::Progress(ProgressEvent::TurnEnded)
        ));
        assert!(matches!(
            translate(&json!({"event": "agent_end"}))[0],
            SessionEvent::Progress(ProgressEvent::TurnEnded)
        ));
    }

    #[test]
    fn turns_tools_approvals_and_prompts_translate() {
        assert!(matches!(
            translate(&json!({"event": "agent_start"}))[0],
            SessionEvent::Progress(ProgressEvent::TurnStarted)
        ));
        assert_eq!(
            translate(&json!({"event": "agent_start"})).len(),
            1,
            "no model named, no model said"
        );
        let named = translate(&json!({"event": "agent_start", "model": "anthropic/claude-opus-5"}));
        assert!(
            matches!(&named[1], SessionEvent::Progress(ProgressEvent::ModelChanged { model }) if model == "anthropic/claude-opus-5")
        );
        assert!(
            matches!(&translate(&json!({"event": "tool_execution_start", "toolName": "read", "input": {"path": "x"}}))[0],
            SessionEvent::Progress(ProgressEvent::ToolStarted { name, tier: ToolTier::Read, .. }) if name == "read")
        );
        assert!(
            matches!(&translate(&json!({"event": "tool_approval_requested", "toolName": "bash", "id": "c1"}))[0],
            SessionEvent::Lifecycle(LifecycleEvent::InputRequested { request }) if request.id == "c1")
        );
        assert!(
            matches!(&translate(&json!({"event": "ui_prompt_start", "message": "Deploy?"}))[0],
            SessionEvent::Lifecycle(LifecycleEvent::InputRequested { request }) if request.summary() == "Deploy?")
        );
        assert!(
            matches!(&translate(&json!({"event": "ui_prompt_end", "id": "p1"}))[0],
            SessionEvent::Lifecycle(LifecycleEvent::InputResolved { id }) if id == "p1")
        );
        assert!(translate(&json!({"event": "message_update"})).is_empty());
        assert!(
            matches!(
                translate(
                    &json!({"event": "tool_execution_end", "toolName": "bash", "isError": true})
                )[0],
                SessionEvent::Progress(ProgressEvent::ToolEnded { ok: false, .. })
            ),
            "a tool that errored says so"
        );
        assert!(matches!(
            translate(&json!({"event": "tool_execution_end", "toolName": "bash"}))[0],
            SessionEvent::Progress(ProgressEvent::ToolEnded { ok: true, .. })
        ));
    }
}
