/**
 * The platform's mark is one file, `logo/logo.svg`: shown by `PlatformMark`,
 * rasterised into the OS icon set by `just app-icon`, drawn or generated by
 * nothing. Source guards, no DOM.
 *
 * Run with `node --test desktop/src/ui/platformMark.test.mjs`.
 */
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..", "..");
const read = (...parts) => readFileSync(join(repo, ...parts), "utf8");

/** Every file under a directory, recursively, as repo-relative paths. */
function walk(dir) {
  const out = [];
  for (const name of readdirSync(join(repo, dir))) {
    const rel = join(dir, name);
    if (statSync(join(repo, rel)).isDirectory()) out.push(...walk(rel));
    else out.push(rel);
  }
  return out;
}

test("logo/logo.svg is one self-contained drawing: titled, sized, fetching nothing, no filter", () => {
  const svg = read("logo", "logo.svg");
  assert.equal(svg.split("<svg").length - 1, 1, "one <svg>");
  assert.match(svg, /<svg[^>]*\sviewBox="[\d.\s-]+"/, "a viewBox, so any size draws it whole");
  assert.ok(svg.includes("<title>Bisa</title>"), "named for the reader who cannot see it");
  for (const forbidden of ["<script", "<filter", "<image", "<foreignObject", "http://www.w3.org/1999/xlink"]) {
    if (forbidden.startsWith("http")) assert.ok(!svg.includes(`href="http`), "no external reference");
    else assert.ok(!svg.includes(forbidden), `no ${forbidden} — resvg draws gradients and clips faithfully; nothing is fetched or run`);
  }
  const declared = new Set([...svg.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
  const used = new Set([...svg.matchAll(/(?:href="#|url\(#)([^")]+)/g)].map((m) => m[1]));
  for (const id of used) assert.ok(declared.has(id), `#${id} is declared in the file`);
  for (const id of declared) assert.ok(used.has(id), `#${id} is used — no dead definition`);
});

test("PlatformMark shows the file and spells no drawing of its own", () => {
  const src = read("desktop", "src", "ui", "PlatformMark.tsx");
  assert.ok(src.includes('from "../../../logo/logo.svg"'), "the one mark, imported as an asset");
  assert.ok(src.includes("<img"), "shown as an image — its ids are never inlined twice");
  assert.ok(!/d="M/.test(src) && !src.includes("<path"), "no path literal in the component");
  const others = walk("desktop/src").filter((p) => /\.(ts|tsx|mjs)$/.test(p) && !p.endsWith("platformMark.test.mjs") && !p.endsWith("PlatformMark.tsx"));
  for (const p of others) assert.ok(!read(p).includes("logo.svg"), `${p} does not name the mark's file — PlatformMark is the one door`);
});

test("the dev server may serve the mark from outside the desktop's root", () => {
  const config = read("desktop", "vite.config.ts");
  assert.ok(config.includes("searchForWorkspaceRoot(process.cwd())"), "the workspace root stays allowed");
  assert.match(config, /allow:\s*\[[^\]]*"\.\.\/logo"/, "and the mark's folder with it");
});

test("the OS icon is rasterised from the same file, and the generator is gone", () => {
  const justfile = read("Justfile");
  assert.match(justfile, /^app-icon:\n\s+cd desktop && npx tauri icon \.\.\/logo\/logo\.svg$/m, "one recipe, one input");
  const files = ["Justfile", ...walk("scripts"), ...walk("desktop/src")].filter((p) => !/\/__pycache__\//.test(p) && !p.endsWith("platformMark.test.mjs"));
  for (const p of files) {
    const text = read(p);
    for (const gone of ["gen-app-icon", "platformMarkPaths", "app-icon.svg"]) assert.ok(!text.includes(gone), `${p} still says ${gone}`);
  }
  assert.ok(!existsSync(join(repo, "desktop", "app-icon.svg")), "no generated SVG beside the app");
});

test("every icon the bundle names exists", () => {
  const conf = JSON.parse(read("desktop", "src-tauri", "tauri.conf.json"));
  const icons = conf.bundle?.icon ?? [];
  assert.ok(icons.length > 0, "the bundle names its icons");
  for (const icon of icons) assert.ok(existsSync(join(repo, "desktop", "src-tauri", icon)), `${icon} is under src-tauri/ — run \`just app-icon\``);
});
