/**
 * The licence as the sources show it (contributing/release.md §Licence):
 * MIT declared once and everywhere, the one allow list carried by both Cargo
 * workspaces and read by the Node gate, the third-party notices generated
 * from NOTICES.md and the dependency graphs and shipped in the bundle, and
 * every obligation the audit named — the MPL files' source, every bundled
 * font, Monaco's attributed material — said in words. Source assertions, no
 * DOM. Run with `node --test desktop/src/scenarios/licences.test.mjs`.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const read = (rel) => readFileSync(join(root, rel), "utf8");
const allowOf = (toml) => [...toml.slice(toml.indexOf("allow = [")).slice(0, toml.slice(toml.indexOf("allow = [")).indexOf("]")).matchAll(/"([^"]+)"/g)].map((m) => m[1]);

test("the platform is MIT: the workspace, every crate, the shell and the licence file say so", () => {
  assert.match(read("Cargo.toml"), /^license = "MIT"$/m);
  for (const c of readdirSync(join(root, "crates"), { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name)) {
    if (c === "bisa-deps") continue;
    assert.ok(read(`crates/${c}/Cargo.toml`).includes("license.workspace = true"), `${c} inherits the licence`);
  }
  assert.match(read("desktop/src-tauri/Cargo.toml"), /^license = "MIT"$/m);
  assert.match(read("LICENSE"), /^MIT License/);
  // The desktop's package is private — never published — and says MIT all
  // the same, as every manifest of the platform does. An assertion here once
  // read `license ?? "MIT"`, which no manifest could fail.
  const desktop = JSON.parse(read("desktop/package.json"));
  assert.equal(desktop.private, true, "the desktop's package is not published");
  assert.equal(desktop.license, "MIT");
  assert.equal(JSON.parse(read("addons/sdk/package.json")).license, "MIT");
});

test("one allow list, carried by both workspaces, with the ids the graphs need and none nobody uses — and never a copyleft or an attribution licence outright", () => {
  const rootList = allowOf(read("deny.toml"));
  const shellList = allowOf(read("desktop/src-tauri/deny.toml"));
  assert.deepEqual(shellList, rootList);
  for (const id of ["MIT", "MIT-0", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib", "0BSD", "Unlicense", "Unicode-3.0", "CC0-1.0", "CDLA-Permissive-2.0", "MPL-2.0", "BSL-1.0"]) assert.ok(rootList.includes(id), id);
  for (const id of ["OpenSSL", "Artistic-2.0", "Unicode-DFS-2016"]) assert.ok(!rootList.includes(id), `${id} is on no graph`);
  assert.ok(!rootList.some((id) => /GPL|CC-BY|OFL/.test(id)), "copyleft never, and OFL is the fonts' — the Node gate adds it for them alone");
  const gate = read("scripts/licences/check-licences.mjs");
  assert.ok(gate.includes('parseAllow(readFileSync(join(root, "deny.toml")') && gate.includes('const FONT_ALLOW = ["OFL-1.1"]'), "the gate reads deny.toml and adds OFL for the fonts");
  assert.ok(!existsSync(join(root, "scripts/check-npm-licences.mjs")), "the old walker with its own list is gone");
  for (const rel of ["Justfile", ".github/workflows/verify.yml", "docs/contributing/setup.md", "docs/contributing/release.md"]) assert.ok(!read(rel).includes("check-npm-licences"), `${rel} names the new gate`);
});

test("the gate runs on both workspaces, locally and in CI, and the notices are checked for staleness", () => {
  const just = read("Justfile");
  assert.ok(just.includes("cargo deny check licenses") && just.includes("cargo deny --manifest-path desktop/src-tauri/Cargo.toml check licenses"), "both workspaces");
  assert.ok(just.includes("node scripts/licences/check-licences.mjs") && just.includes("gen-notices:") && just.includes("check-notices:"));
  assert.match(just, /^verify:.*licence-gate check-notices/m);
  const ci = read(".github/workflows/verify.yml");
  assert.equal((ci.match(/EmbarkStudios\/cargo-deny-action@v2/g) ?? []).length, 2, "cargo-deny twice: the root and the shell");
  assert.ok(ci.includes("manifest-path: desktop/src-tauri/Cargo.toml") && ci.includes("scripts/licences/check-licences.mjs") && ci.includes("gen-third-party-notices.mjs --stdout"));
});

test("the third-party notices are generated from NOTICES.md and the graphs, name every obligation, and ship in the bundle", () => {
  const notices = read("THIRD-PARTY-NOTICES.md");
  const hand = read("NOTICES.md");
  assert.ok(notices.startsWith("# Third-party notices\n\n<!-- Generated by `just gen-notices`"), "generated, and says so");
  const body = hand.replace(/^# Third-party notices\n+/, "");
  assert.ok(notices.includes(body.trim().slice(0, 400)), "NOTICES.md is carried verbatim");
  for (const word of ["attohttpc", "option-ext", "https://crates.io/crates/option-ext", "### MPL-2.0", "### OFL-1.1", "### Apache-2.0", "### MIT", "monaco-editor", "ThirdPartyNotices"]) assert.ok(notices.includes(word), `the notices name ${word}`);
  for (const font of ["Inter", "Atkinson Hyperlegible", "JetBrains Mono", "IBM Plex Mono", "Excalifont", "Virgil", "Cascadia Code", "Liberation Sans", "Lilita One", "Nunito", "Assistant", "Xiaolai", "Comic Shanns"]) assert.ok(hand.includes(font), `NOTICES.md names the font ${font}`);
  assert.ok(hand.includes("Codicons") && hand.includes("WHATWG") && hand.includes("Attribution 4.0"), "Monaco's attributed material is named");
  assert.ok(hand.includes("Mozilla Public License 2.0") && hand.includes("§3.2"), "the MPL files and where their source is");
  const lib = read("scripts/macos/lib.sh");
  assert.ok(lib.includes('cp "$root/LICENSE" "$stage/Contents/Resources/LICENSE"') && lib.includes('cp "$root/THIRD-PARTY-NOTICES.md" "$stage/Contents/Resources/THIRD-PARTY-NOTICES.md"'), "both files ship, in every bundle the library assembles");
  assert.ok(read("README.md").includes("THIRD-PARTY-NOTICES.md"));
});

test("About reveals the licence and the notices where the shell found them", () => {
  const main = read("desktop/src-tauri/src/main.rs");
  assert.ok(main.includes("fn licence_files(") && main.includes('find("LICENSE")') && main.includes('find("THIRD-PARTY-NOTICES.md")') && main.includes("licence_files,"), "the command and its registration");
  const about = read("desktop/src/shell/AboutDialog.tsx");
  assert.ok(about.includes('invoke<LicenceFiles>("licence_files")') && about.includes("aboutFiles(shipped.data)") && about.includes("revealPath(f.path)"), "About asks the shell and reveals");
});
